import streamlit as st
import pandas as pd
from datetime import datetime, timedelta
import json
import uuid
from typing import Dict, List, Optional
import base64
from io import BytesIO

class DocumentGenerator:
    """Document Generator for RIPT system - generates trade documents, compliance reports, and certificates"""
    
    def __init__(self):
        self.document_types = [
            "Trade Settlement Certificate",
            "SRVA Account Statement", 
            "Compliance Report",
            "Transaction Summary",
            "Exchange Rate Certificate",
            "Audit Trail Report",
            "KYC Document",
            "FEMA Compliance Certificate",
            "Export/Import License",
            "Bank Statement"
        ]
        
        self.templates = {
            "Trade Settlement Certificate": self._generate_settlement_certificate,
            "SRVA Account Statement": self._generate_account_statement,
            "Compliance Report": self._generate_compliance_report,
            "Transaction Summary": self._generate_transaction_summary,
            "Exchange Rate Certificate": self._generate_exchange_rate_certificate
        }
    
    def show_interface(self):
        """Display document generator interface"""
        st.header("📄 Document Generator")
        st.markdown("Generate official trade documents, compliance reports, and certificates")
        
        tab1, tab2, tab3, tab4 = st.tabs([
            "📑 Generate Documents", 
            "📊 Bulk Generation", 
            "🗂️ Document Templates", 
            "📚 Document Library"
        ])
        
        with tab1:
            self._show_single_document_generator()
        
        with tab2:
            self._show_bulk_generator()
        
        with tab3:
            self._show_templates()
        
        with tab4:
            self._show_document_library()
    
    def _show_single_document_generator(self):
        """Single document generation interface"""
        st.subheader("Generate Single Document")
        
        col1, col2 = st.columns([1, 1])
        
        with col1:
            st.markdown("#### Document Configuration")
            
            document_type = st.selectbox("Document Type", self.document_types)
            
            # Dynamic form based on document type
            if document_type == "Trade Settlement Certificate":
                transaction_id = st.text_input("Transaction ID", value="TXN-20250813-001")
                settlement_amount = st.number_input("Settlement Amount (₹)", min_value=0.01, value=100000.0)
                settlement_date = st.date_input("Settlement Date", datetime.now().date())
                from_country = st.selectbox("From Country", ["Russia", "Germany", "UK", "Singapore"])
                to_country = st.selectbox("To Country", ["India"], disabled=True)
                
            elif document_type == "SRVA Account Statement":
                account_id = st.text_input("Account ID", value="SRVA-RUS-001")
                statement_period = st.selectbox("Period", ["Monthly", "Quarterly", "Yearly"])
                start_date = st.date_input("Start Date", datetime.now().date() - timedelta(days=30))
                end_date = st.date_input("End Date", datetime.now().date())
                
            elif document_type == "Compliance Report":
                report_type = st.selectbox("Report Type", ["RBI Compliance", "FEMA Compliance", "AML Report"])
                reporting_period = st.selectbox("Period", ["Monthly", "Quarterly", "Annual"])
                compliance_officer = st.text_input("Compliance Officer", value="Officer Name")
                
            # Document metadata
            st.markdown("#### Document Metadata")
            reference_number = st.text_input("Reference Number", value=f"DOC-{datetime.now().strftime('%Y%m%d%H%M%S')}")
            generated_by = st.text_input("Generated By", value="RIPT System")
            
            # Additional options
            include_watermark = st.checkbox("Include Watermark", value=True)
            include_digital_signature = st.checkbox("Include Digital Signature", value=True)
            
        with col2:
            st.markdown("#### Document Preview")
            
            if st.button("🔍 Generate Preview", type="primary"):
                # Prepare document data
                document_data = {
                    'document_type': document_type,
                    'reference_number': reference_number,
                    'generated_by': generated_by,
                    'generation_date': datetime.now(),
                    'include_watermark': include_watermark,
                    'include_digital_signature': include_digital_signature
                }
                
                # Add specific data based on document type
                if document_type == "Trade Settlement Certificate":
                    document_data.update({
                        'transaction_id': transaction_id,
                        'settlement_amount': settlement_amount,
                        'settlement_date': settlement_date,
                        'from_country': from_country,
                        'to_country': to_country
                    })
                elif document_type == "SRVA Account Statement":
                    document_data.update({
                        'account_id': account_id,
                        'statement_period': statement_period,
                        'start_date': start_date,
                        'end_date': end_date
                    })
                elif document_type == "Compliance Report":
                    document_data.update({
                        'report_type': report_type,
                        'reporting_period': reporting_period,
                        'compliance_officer': compliance_officer
                    })
                
                # Generate document
                document_content = self._generate_document(document_data)
                
                if document_content:
                    st.success("✅ Document generated successfully!")
                    
                    # Display document preview
                    st.markdown("##### 📄 Document Content")
                    st.markdown(document_content, unsafe_allow_html=True)
                    
                    # Download button
                    st.download_button(
                        label="📥 Download Document",
                        data=document_content,
                        file_name=f"{reference_number}_{document_type.replace(' ', '_')}.html",
                        mime="text/html"
                    )
                    
                    # Save to session for library
                    if 'generated_documents' not in st.session_state:
                        st.session_state.generated_documents = []
                    
                    st.session_state.generated_documents.append({
                        'reference_number': reference_number,
                        'document_type': document_type,
                        'generated_date': datetime.now(),
                        'content': document_content,
                        'metadata': document_data
                    })
                
                else:
                    st.error("❌ Failed to generate document")
    
    def _show_bulk_generator(self):
        """Bulk document generation interface"""
        st.subheader("Bulk Document Generation")
        
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("#### Bulk Generation Options")
            
            bulk_type = st.selectbox("Bulk Generation Type", [
                "All Pending Transactions",
                "Monthly Account Statements",
                "Compliance Reports",
                "Settlement Certificates"
            ])
            
            document_format = st.selectbox("Output Format", ["HTML", "PDF", "Word Document"])
            
            if bulk_type == "All Pending Transactions":
                min_amount = st.number_input("Minimum Amount Filter (₹)", value=0.0)
                
            elif bulk_type == "Monthly Account Statements":
                target_month = st.selectbox("Target Month", [
                    "Current Month", "Last Month", "Custom"
                ])
                
                if target_month == "Custom":
                    custom_month = st.date_input("Select Month", datetime.now().date())
            
            batch_size = st.slider("Batch Size", 1, 100, 10)
            
        with col2:
            st.markdown("#### Bulk Processing")
            
            if st.button("🚀 Start Bulk Generation", type="primary"):
                progress_bar = st.progress(0)
                status_text = st.empty()
                
                # Simulate bulk generation
                total_documents = batch_size
                generated_docs = []
                
                for i in range(total_documents):
                    progress = (i + 1) / total_documents
                    progress_bar.progress(progress)
                    status_text.text(f"Generating document {i+1} of {total_documents}...")
                    
                    # Generate mock document
                    doc_data = {
                        'document_type': bulk_type,
                        'reference_number': f"BULK-{datetime.now().strftime('%Y%m%d')}-{i+1:03d}",
                        'generated_by': 'RIPT Bulk Generator',
                        'generation_date': datetime.now(),
                        'batch_id': f"BATCH-{datetime.now().strftime('%Y%m%d%H%M%S')}"
                    }
                    
                    doc_content = self._generate_document(doc_data)
                    generated_docs.append({
                        'reference': doc_data['reference_number'],
                        'content': doc_content
                    })
                
                status_text.text("✅ Bulk generation completed!")
                st.success(f"Successfully generated {len(generated_docs)} documents")
                
                # Download all as ZIP would be implemented here
                st.info("💡 In production, documents would be packaged as ZIP file for download")
    
    def _show_templates(self):
        """Document templates interface"""
        st.subheader("Document Templates Management")
        
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("#### Available Templates")
            
            template_list = list(self.templates.keys())
            selected_template = st.selectbox("Select Template", template_list)
            
            st.markdown("##### Template Information")
            template_info = self._get_template_info(selected_template)
            
            for key, value in template_info.items():
                st.write(f"**{key}:** {value}")
            
            if st.button("📄 Preview Template"):
                sample_data = self._get_sample_data(selected_template)
                preview_content = self._generate_document(sample_data)
                
                if preview_content:
                    st.markdown("##### Template Preview")
                    st.markdown(preview_content, unsafe_allow_html=True)
        
        with col2:
            st.markdown("#### Template Customization")
            
            st.info("🔧 Template customization features would include:")
            st.markdown("""
            - Custom header/footer design
            - Logo and branding options
            - Field mapping configuration
            - Conditional content sections
            - Multi-language support
            - Digital signature placement
            """)
            
            # Template editor mockup
            st.markdown("##### Template Editor")
            custom_header = st.text_area("Custom Header", 
                value="<h1>RIPT - Rupee Intelligence Platform Trade</h1>")
            
            custom_footer = st.text_area("Custom Footer",
                value="<p>This document is electronically generated by RIPT system.</p>")
            
            if st.button("💾 Save Template Changes"):
                st.success("Template changes saved successfully!")
    
    def _show_document_library(self):
        """Document library interface"""
        st.subheader("Document Library")
        
        if 'generated_documents' in st.session_state and st.session_state.generated_documents:
            documents = st.session_state.generated_documents
            
            # Summary metrics
            col1, col2, col3, col4 = st.columns(4)
            
            with col1:
                st.metric("Total Documents", len(documents))
            
            with col2:
                doc_types = [doc['document_type'] for doc in documents]
                unique_types = len(set(doc_types))
                st.metric("Document Types", unique_types)
            
            with col3:
                today_docs = len([doc for doc in documents 
                                if doc['generated_date'].date() == datetime.now().date()])
                st.metric("Generated Today", today_docs)
            
            with col4:
                # Calculate total size (mock)
                total_size = len(documents) * 50  # KB
                st.metric("Total Size", f"{total_size} KB")
            
            # Document list
            st.markdown("#### Document List")
            
            document_df = pd.DataFrame([
                {
                    'Reference': doc['reference_number'],
                    'Type': doc['document_type'],
                    'Generated': doc['generated_date'].strftime('%Y-%m-%d %H:%M'),
                    'Size': f"{len(doc['content'])//1000} KB"
                }
                for doc in documents
            ])
            
            st.dataframe(document_df, use_container_width=True)
            
            # Document viewer
            st.markdown("#### Document Viewer")
            
            selected_ref = st.selectbox("Select Document to View", 
                                      [doc['reference_number'] for doc in documents])
            
            if selected_ref:
                selected_doc = next((doc for doc in documents 
                                   if doc['reference_number'] == selected_ref), None)
                
                if selected_doc:
                    col1, col2 = st.columns([3, 1])
                    
                    with col1:
                        st.markdown("##### Document Content")
                        st.markdown(selected_doc['content'], unsafe_allow_html=True)
                    
                    with col2:
                        st.markdown("##### Actions")
                        
                        if st.button("📥 Download"):
                            st.download_button(
                                label="Download HTML",
                                data=selected_doc['content'],
                                file_name=f"{selected_ref}.html",
                                mime="text/html"
                            )
                        
                        if st.button("📧 Email"):
                            st.info("Email functionality would be implemented here")
                        
                        if st.button("🗑️ Delete"):
                            documents.remove(selected_doc)
                            st.success("Document deleted")
                            st.rerun()
        
        else:
            st.info("📚 No documents in library. Generate some documents to see them here.")
            
            if st.button("📄 Generate Sample Documents"):
                # Generate some sample documents
                sample_docs = []
                
                for i in range(3):
                    doc_data = {
                        'document_type': 'Trade Settlement Certificate',
                        'reference_number': f"SAMPLE-{i+1:03d}",
                        'generated_by': 'RIPT System',
                        'generation_date': datetime.now(),
                        'transaction_id': f"TXN-SAMPLE-{i+1}",
                        'settlement_amount': (i+1) * 50000,
                        'settlement_date': datetime.now().date(),
                        'from_country': ['Russia', 'Germany', 'UK'][i],
                        'to_country': 'India'
                    }
                    
                    content = self._generate_document(doc_data)
                    
                    sample_docs.append({
                        'reference_number': doc_data['reference_number'],
                        'document_type': doc_data['document_type'],
                        'generated_date': datetime.now(),
                        'content': content,
                        'metadata': doc_data
                    })
                
                st.session_state.generated_documents = sample_docs
                st.success("✅ Sample documents generated!")
                st.rerun()
    
    def _generate_document(self, document_data: Dict) -> str:
        """Generate document based on type and data"""
        document_type = document_data['document_type']
        
        if document_type in self.templates:
            return self.templates[document_type](document_data)
        else:
            return self._generate_generic_document(document_data)
    
    def _generate_settlement_certificate(self, data: Dict) -> str:
        """Generate trade settlement certificate"""
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Trade Settlement Certificate</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                .header {{ text-align: center; border-bottom: 2px solid #1f77b4; padding-bottom: 20px; }}
                .content {{ margin: 30px 0; }}
                .field {{ margin: 10px 0; }}
                .signature {{ margin-top: 50px; }}
                .watermark {{ position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); 
                            font-size: 72px; color: rgba(31, 119, 180, 0.1); z-index: -1; }}
            </style>
        </head>
        <body>
            {'<div class="watermark">RIPT OFFICIAL</div>' if data.get('include_watermark') else ''}
            
            <div class="header">
                <h1>🏦 RIPT - Rupee Intelligence Platform Trade</h1>
                <h2>TRADE SETTLEMENT CERTIFICATE</h2>
                <p>Reference No: {data.get('reference_number', 'N/A')}</p>
            </div>
            
            <div class="content">
                <div class="field"><strong>Transaction ID:</strong> {data.get('transaction_id', 'N/A')}</div>
                <div class="field"><strong>Settlement Amount:</strong> ₹{data.get('settlement_amount', 0):,.2f}</div>
                <div class="field"><strong>Settlement Date:</strong> {data.get('settlement_date', 'N/A')}</div>
                <div class="field"><strong>From Country:</strong> {data.get('from_country', 'N/A')}</div>
                <div class="field"><strong>To Country:</strong> {data.get('to_country', 'India')}</div>
                <div class="field"><strong>Generation Date:</strong> {data.get('generation_date', datetime.now()).strftime('%Y-%m-%d %H:%M:%S')}</div>
                
                <p style="margin-top: 30px;">
                This certificate confirms that the above mentioned trade settlement has been processed 
                through the Special Rupee Vostro Account (SRVA) mechanism in compliance with RBI guidelines 
                and FEMA regulations.
                </p>
                
                <div class="signature">
                    <p><strong>Generated By:</strong> {data.get('generated_by', 'RIPT System')}</p>
                    {'<p><strong>Digital Signature:</strong> [ELECTRONICALLY SIGNED]</p>' if data.get('include_digital_signature') else ''}
                    <p><strong>Certificate Valid Until:</strong> {(datetime.now() + timedelta(days=365)).strftime('%Y-%m-%d')}</p>
                </div>
            </div>
        </body>
        </html>
        """
    
    def _generate_account_statement(self, data: Dict) -> str:
        """Generate SRVA account statement"""
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>SRVA Account Statement</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                .header {{ text-align: center; border-bottom: 2px solid #1f77b4; padding-bottom: 20px; }}
                .content {{ margin: 30px 0; }}
                .field {{ margin: 10px 0; }}
                table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #f2f2f2; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🏦 RIPT - SRVA Account Statement</h1>
                <p>Account ID: {data.get('account_id', 'N/A')}</p>
                <p>Statement Period: {data.get('statement_period', 'N/A')}</p>
            </div>
            
            <div class="content">
                <div class="field"><strong>Statement Period:</strong> {data.get('start_date', 'N/A')} to {data.get('end_date', 'N/A')}</div>
                <div class="field"><strong>Generated On:</strong> {data.get('generation_date', datetime.now()).strftime('%Y-%m-%d %H:%M:%S')}</div>
                
                <h3>Account Summary</h3>
                <table>
                    <tr><th>Opening Balance</th><td>₹1,50,000.00</td></tr>
                    <tr><th>Total Credits</th><td>₹5,75,000.00</td></tr>
                    <tr><th>Total Debits</th><td>₹3,25,000.00</td></tr>
                    <tr><th>Closing Balance</th><td>₹4,00,000.00</td></tr>
                </table>
                
                <h3>Transaction Details</h3>
                <table>
                    <tr>
                        <th>Date</th>
                        <th>Description</th>
                        <th>Debit</th>
                        <th>Credit</th>
                        <th>Balance</th>
                    </tr>
                    <tr>
                        <td>2024-08-01</td>
                        <td>Export Settlement - TXN001</td>
                        <td>-</td>
                        <td>₹2,50,000</td>
                        <td>₹4,00,000</td>
                    </tr>
                    <tr>
                        <td>2024-08-05</td>
                        <td>Import Payment - TXN002</td>
                        <td>₹1,50,000</td>
                        <td>-</td>
                        <td>₹2,50,000</td>
                    </tr>
                </table>
                
                <p style="margin-top: 30px; font-size: 12px;">
                This statement is generated electronically and does not require physical signature.
                For any queries, please contact RIPT Support.
                </p>
            </div>
        </body>
        </html>
        """
    
    def _generate_compliance_report(self, data: Dict) -> str:
        """Generate compliance report"""
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Compliance Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                .header {{ text-align: center; border-bottom: 2px solid #1f77b4; padding-bottom: 20px; }}
                .content {{ margin: 30px 0; }}
                .field {{ margin: 10px 0; }}
                .compliant {{ color: green; font-weight: bold; }}
                .non-compliant {{ color: red; font-weight: bold; }}
                table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #f2f2f2; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🔍 RIPT Compliance Report</h1>
                <h2>{data.get('report_type', 'General Compliance Report')}</h2>
                <p>Reporting Period: {data.get('reporting_period', 'N/A')}</p>
            </div>
            
            <div class="content">
                <div class="field"><strong>Report Generated:</strong> {data.get('generation_date', datetime.now()).strftime('%Y-%m-%d %H:%M:%S')}</div>
                <div class="field"><strong>Compliance Officer:</strong> {data.get('compliance_officer', 'N/A')}</div>
                <div class="field"><strong>Reference Number:</strong> {data.get('reference_number', 'N/A')}</div>
                
                <h3>Compliance Status Summary</h3>
                <table>
                    <tr>
                        <th>Compliance Area</th>
                        <th>Status</th>
                        <th>Last Review</th>
                        <th>Next Review</th>
                    </tr>
                    <tr>
                        <td>RBI Guidelines</td>
                        <td><span class="compliant">COMPLIANT</span></td>
                        <td>2024-08-10</td>
                        <td>2024-09-10</td>
                    </tr>
                    <tr>
                        <td>FEMA Regulations</td>
                        <td><span class="compliant">COMPLIANT</span></td>
                        <td>2024-08-08</td>
                        <td>2024-11-08</td>
                    </tr>
                    <tr>
                        <td>AML/CFT</td>
                        <td><span class="compliant">COMPLIANT</span></td>
                        <td>2024-08-12</td>
                        <td>2024-08-26</td>
                    </tr>
                    <tr>
                        <td>KYC Documentation</td>
                        <td><span class="non-compliant">REVIEW REQUIRED</span></td>
                        <td>2024-07-15</td>
                        <td>2024-08-15</td>
                    </tr>
                </table>
                
                <h3>Key Findings</h3>
                <ul>
                    <li>All SRVA transactions comply with RBI guidelines</li>
                    <li>Exchange rate documentation is complete and accurate</li>
                    <li>3 KYC documents require renewal within 30 days</li>
                    <li>No suspicious transaction patterns detected</li>
                </ul>
                
                <h3>Recommendations</h3>
                <ul>
                    <li>Update KYC documentation for flagged accounts</li>
                    <li>Implement monthly compliance review schedule</li>
                    <li>Enhance transaction monitoring algorithms</li>
                </ul>
                
                <div style="margin-top: 50px;">
                    <p><strong>Compliance Officer Signature:</strong> [ELECTRONICALLY SIGNED]</p>
                    <p><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d')}</p>
                </div>
            </div>
        </body>
        </html>
        """
    
    def _generate_transaction_summary(self, data: Dict) -> str:
        """Generate transaction summary"""
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Transaction Summary</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                .header {{ text-align: center; border-bottom: 2px solid #1f77b4; padding-bottom: 20px; }}
                .content {{ margin: 30px 0; }}
                table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #f2f2f2; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>💱 Transaction Summary Report</h1>
                <p>Generated: {data.get('generation_date', datetime.now()).strftime('%Y-%m-%d %H:%M:%S')}</p>
            </div>
            
            <div class="content">
                <h3>Summary Statistics</h3>
                <table>
                    <tr><th>Total Transactions</th><td>156</td></tr>
                    <tr><th>Total Volume</th><td>₹45,67,89,000</td></tr>
                    <tr><th>Completed</th><td>142 (91.0%)</td></tr>
                    <tr><th>Pending</th><td>14 (9.0%)</td></tr>
                </table>
                
                <h3>Recent Transactions</h3>
                <table>
                    <tr>
                        <th>Transaction ID</th>
                        <th>Date</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Country</th>
                    </tr>
                    <tr>
                        <td>TXN-20240813-001</td>
                        <td>2024-08-13</td>
                        <td>₹2,50,000</td>
                        <td>Completed</td>
                        <td>Russia</td>
                    </tr>
                    <tr>
                        <td>TXN-20240813-002</td>
                        <td>2024-08-13</td>
                        <td>₹1,75,000</td>
                        <td>Pending</td>
                        <td>Germany</td>
                    </tr>
                </table>
            </div>
        </body>
        </html>
        """
    
    def _generate_exchange_rate_certificate(self, data: Dict) -> str:
        """Generate exchange rate certificate"""
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Exchange Rate Certificate</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                .header {{ text-align: center; border-bottom: 2px solid #1f77b4; padding-bottom: 20px; }}
                .content {{ margin: 30px 0; }}
                .field {{ margin: 10px 0; }}
                table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: center; }}
                th {{ background-color: #f2f2f2; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>💹 Exchange Rate Certificate</h1>
                <p>Reference: {data.get('reference_number', 'N/A')}</p>
            </div>
            
            <div class="content">
                <div class="field"><strong>Certification Date:</strong> {data.get('generation_date', datetime.now()).strftime('%Y-%m-%d %H:%M:%S')}</div>
                <div class="field"><strong>Valid Until:</strong> {(datetime.now() + timedelta(hours=24)).strftime('%Y-%m-%d %H:%M:%S')}</div>
                
                <h3>Certified Exchange Rates (INR)</h3>
                <table>
                    <tr>
                        <th>Currency</th>
                        <th>Rate (per 1 INR)</th>
                        <th>Last Updated</th>
                    </tr>
                    <tr><td>USD</td><td>0.01202</td><td>{datetime.now().strftime('%H:%M:%S')}</td></tr>
                    <tr><td>EUR</td><td>0.01106</td><td>{datetime.now().strftime('%H:%M:%S')}</td></tr>
                    <tr><td>GBP</td><td>0.00946</td><td>{datetime.now().strftime('%H:%M:%S')}</td></tr>
                    <tr><td>RUB</td><td>1.0989</td><td>{datetime.now().strftime('%H:%M:%S')}</td></tr>
                </table>
                
                <p style="margin-top: 30px;">
                This certificate confirms the exchange rates used for SRVA transactions processed through
                the RIPT system. Rates are sourced from authorized providers and comply with RBI guidelines.
                </p>
                
                <div style="margin-top: 50px;">
                    <p><strong>Certified By:</strong> RIPT Exchange Rate Module</p>
                    <p><strong>Digital Signature:</strong> [ELECTRONICALLY SIGNED]</p>
                </div>
            </div>
        </body>
        </html>
        """
    
    def _generate_generic_document(self, data: Dict) -> str:
        """Generate generic document for unsupported types"""
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>{data.get('document_type', 'Document')}</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                .header {{ text-align: center; border-bottom: 2px solid #1f77b4; padding-bottom: 20px; }}
                .content {{ margin: 30px 0; }}
                .field {{ margin: 10px 0; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🏦 RIPT Document</h1>
                <h2>{data.get('document_type', 'Generic Document')}</h2>
            </div>
            
            <div class="content">
                <div class="field"><strong>Reference Number:</strong> {data.get('reference_number', 'N/A')}</div>
                <div class="field"><strong>Generated:</strong> {data.get('generation_date', datetime.now()).strftime('%Y-%m-%d %H:%M:%S')}</div>
                <div class="field"><strong>Generated By:</strong> {data.get('generated_by', 'RIPT System')}</div>
                
                <p>This is a generic document template. Specific content would be added based on document type.</p>
                
                <div style="margin-top: 50px;">
                    <p><strong>Document Data:</strong></p>
                    <pre>{json.dumps(data, indent=2, default=str)}</pre>
                </div>
            </div>
        </body>
        </html>
        """
    
    def _get_template_info(self, template_name: str) -> Dict:
        """Get template information"""
        template_info = {
            "Trade Settlement Certificate": {
                "Description": "Official certificate for completed trade settlements",
                "Fields Required": "Transaction ID, Amount, Countries, Settlement Date",
                "Compliance": "RBI & FEMA compliant",
                "Validity": "1 year from generation"
            },
            "SRVA Account Statement": {
                "Description": "Detailed account statement for SRVA accounts",
                "Fields Required": "Account ID, Period, Transaction History",
                "Compliance": "Banking regulation compliant",
                "Validity": "Valid for current period"
            },
            "Compliance Report": {
                "Description": "Comprehensive compliance status report",
                "Fields Required": "Report Type, Period, Officer Details",
                "Compliance": "Regulatory reporting standard",
                "Validity": "Based on reporting frequency"
            }
        }
        
        return template_info.get(template_name, {
            "Description": "Generic document template",
            "Fields Required": "Basic metadata",
            "Compliance": "Standard format",
            "Validity": "As specified"
        })
    
    def _get_sample_data(self, template_name: str) -> Dict:
        """Get sample data for template preview"""
        base_data = {
            'document_type': template_name,
            'reference_number': f"SAMPLE-{datetime.now().strftime('%Y%m%d%H%M%S')}",
            'generated_by': 'RIPT System',
            'generation_date': datetime.now(),
            'include_watermark': True,
            'include_digital_signature': True
        }
        
        if template_name == "Trade Settlement Certificate":
            base_data.update({
                'transaction_id': 'TXN-SAMPLE-001',
                'settlement_amount': 250000.0,
                'settlement_date': datetime.now().date(),
                'from_country': 'Russia',
                'to_country': 'India'
            })
        elif template_name == "SRVA Account Statement":
            base_data.update({
                'account_id': 'SRVA-SAMPLE-001',
                'statement_period': 'Monthly',
                'start_date': datetime.now().date() - timedelta(days=30),
                'end_date': datetime.now().date()
            })
        elif template_name == "Compliance Report":
            base_data.update({
                'report_type': 'RBI Compliance',
                'reporting_period': 'Monthly',
                'compliance_officer': 'Sample Officer'
            })
        
        return base_data
    
    def get_document_stats(self) -> Dict:
        """Get document generation statistics"""
        if 'generated_documents' not in st.session_state:
            return {
                'total_documents': 0,
                'documents_today': 0,
                'document_types': 0,
                'total_size_kb': 0
            }
        
        documents = st.session_state.generated_documents
        today = datetime.now().date()
        
        return {
            'total_documents': len(documents),
            'documents_today': len([doc for doc in documents 
                                  if doc['generated_date'].date() == today]),
            'document_types': len(set(doc['document_type'] for doc in documents)),
            'total_size_kb': sum(len(doc['content']) for doc in documents) // 1000
        }
